// try catch 

try{// execute esse bloco e caso der erro
    console.log(naoExisto);
}catch(err){ // execute esse caso o de cima de erro
    console.log('naoExisto nao existe'); // mensagem do erro    
}